CREATE TABLE "MEMBER"(
     MEMBER_ID VARCHAR2(50),
     MEMBER_NICKNAME VARCHAR2(50),
     MEMBER_PW VARCHAR2(50),
     MEMBER_PW_CHECK VARCHAR2(50),
     MEMBER_EMAIL VARCHAR2(50),
     MEMBER_GENDER VARCHAR2(50),
     MEMBER_BIRTH VARCHAR2(20),
     MEMBER_HP VARCHAR2(20),
     MEMBER_ADDRESS VARCHAR2(200),
     MEMBER_BLOGMAIL VARCHAR2(50),
     MEMBER_ADDRESS_DETAIL VARCHAR2(200),
     MEMBER_ADDRESS_ETC VARCHAR2(200),
     MEMBER_ACTIVE_PLACE VARCHAR2(50),
     CONSTRAINTS MEMBER_PK PRIMARY KEY(MEMBER_ID)
);

ALTER TABLE "MEMBER" ADD(ADMIN VARCHAR2(5) DEFAULT NULL);
ALTER TABLE "MEMBER" ADD(MEMBER_PW_CHECK VARCHAR2(50));
SELECT *FROM "MEMBER";
ALTER TABLE "MEMBER" DROP COLUMN ADMIN;

DROP TABLE "MEMBER" CASCADE CONSTRAINTS;

INSERT INTO "MEMBER"
VALUES('admin', 'admin', 'ki0707','ki0707', 'kbmin2@naver.com','Man','birth','01067870761','서울성동구금호동','kbmin2@naver.com','서울시','주소etc','장소');

SELECT NAME FROM V$DATABASE;  
