CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;

DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE GROUP_JOINED_SEQ;
DROP SEQUENCE GROUP_SEQ;




DROP TABLE BOARD CASCADE CONSTRAINTS;
SELECT * FROM BOARD;

CREATE TABLE BOARD(
   BOARD_NUM NUMBER(10),
   BOARD_TITLE VARCHAR2(100),
   BOARD_CONTENTS VARCHAR2(600),
   BOARD_DATE DATE,
   BOARD_READCOUNT NUMBER(30),
   CONSTRAINTS BOARD_PK PRIMARY KEY(BOARD_NUM)
);

INSERT INTO BOARD
VALUES(1 '테스트제목6입니다', '테스트내용3dfdfdfdfdfddfd', SYSDATE, 0);



-------------------------------------------GROUP TABLE
CREATE TABLE "GROUP"(
	GROUP_NUM NUMBER(10),
	GROUP_NAME VARCHAR2(50),
	GROUP_CONTENTS VARCHAR2(50),
	GROUP_INFO VARCHAR2(50),
	GROUP_INFO_TWO VARCHAR2(50),
	GROUP_INFO_THREE VARCHAR2(50),
	MEMBER_ID VARCHAR2(50),
	MEMBER_NUM NUMBER(10),
	MEMBER_MAX NUMBER(10),
	GROUP_IMG VARCHAR2(50),
	GROUP_REGION VARCHAR2(50),
	GROUP_REGISTER_DATE VARCHAR2(50),
	GROUP_REVIEW_DATE VARCHAR2(50),
	GROUP_REVIEWER_DATE VARCHAR2(50),
	GROUP_IMGMAIN VARCHAR2(50),
	CONSTRAINTS GROUP_PK PRIMARY KEY(GROUP_NUM)
);	

ALTER TABLE "GROUP" ADD UNIQUE (GROUP_NAME);


INSERT INTO "GROUP" 
VALUES(
5 , '그룹이름5', '그룹상세내용','#헤어살롱 #인생머리','[서울 동대문]','인생머리 만들어 들어요','그룹아이디', 1 , 100 ,'assets/img/gallery/hairPost.png','그룹지역','12/21(registerDate)','reviewDate','reviewerDate','IMGMAIN');

INSERT INTO "GROUP"
VALUES(
2 , '그룹 이름', '그룹상세내용','#서울숲 #카페','[서울 서울숲역]','분위기 카페','그룹아이디', 1 , 10 , 'assets/img/blog/single_blog_5.png','그룹지역','IMGMAIN 경로')


INSERT INTO "GROUP"
VALUES(
3, '그룹이름2', '그룹상세내용2','#그룹정보2','[그룹위치]','그룹정보2','그룹아이디2','그룹인원2','그룹인원MAX2','이미지경로2','그룹지역2');
INSERT INTO "GROUP"
VALUES(
3, '그룹이름3', '그룹정보3','멤버 ID3','그룹인원3','그룹인원제한3','그룹이미지3','그룹지역3');

INSERT INTO "GROUP"
VALUES(
4, '그룹이름4','그룹정보4','멤버 ID4','그룹인원4','그룹인원제한4','그룹이미지4','그룹지역4');


UPDATE "GROUP"
		SET MEMBER_NUM = MEMBER_NUM + 1
		WHERE GROUP_NUM = ${group_num}

SELECT * FROM "GROUP";

SELECT * FROM
			(SELECT ROWNUM R, D.* FROM 
				(SELECT * FROM "GROUP" ORDER BY GROUP_NUM DESC) D) B
				 WHERE B.R BETWEEN ${startRow} AND ${endRow}

SELECT GROUP_SEQ.CURRAVAL FROM DUAL;
SELECT * FROM "GROUP" WHERE GROUP_NUM = ${group_num};



select tb_id_sequence.nextval, tb_id_sequence.currval from dual;

SELECT GROUP_SEQ.NEXTVAL,GROUP_SEQ.CURRAVAL FROM DUAL;

select * from user_sequences


DROP TABLE "GROUP" CASCADE CONSTRAINTS;


CREATE SEQUENCE GROUP_SEQ
INCREMENT BY 1
START WITH 4
MINVALUE 4
MAXVALUE 100000;
--------------------------------그룹 조인 테이블 ------------------

CREATE TABLE GROUP_JOINED(
    GROUPJOINED_NUM NUMBER(10),
    GROUP_NUM NUMBER(10),
    GROUP_NAME VARCHAR2(50),
    MEMBER_ID VARCHAR2(50),
    BLOG_MAIL VARCHAR2(50),
    MEMBER_NAME VARCHAR2(50),
    MEMBER_HP VARCHAR2(50),
    MEMBER_ZIPCODE VARCHAR2(100),
    MEMBER_ADDRESS VARCHAR2(100),
    MEMBER_ADDRESS_DETAIL VARCHAR2(100),
    MEMBER_ADDRESS_ETC VARCHAR2(100),
    CONSTRAINTS JOINED_GROUPNUM_FK FOREIGN KEY(GROUP_NUM) REFERENCES "GROUP"(GROUP_NUM),
    CONSTRAINTS JOINED_GROUPNAME_FK FOREIGN KEY(GROUP_NAME) REFERENCES "GROUP"(GROUP_NAME),
    CONSTRAINTS JOINED_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES "MEMBER"(MEMBER_ID)
);

SELECT * FROM GROUP_JOINED; 

DROP TABLE GROUP_JOINED; 

CREATE SEQUENCE GROUPJOINED_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;


SELECT GROUPJOINED_SEQ.CURRVAL FROM DUAL;
--------------------------------댓글 테이블 ------------------
CREATE TABLE REPLY (
REPLY_NUM NUMBER(10),
GROUP_NUM NUMBER(10),
MEMBER_ID VARCHAR2(50),
REPLY_CONTENTS VARCHAR2(3000),
CONSTRAINTS REPLY_PK PRIMARY KEY(REPLY_NUM),
CONSTRAINTS REPLY_FK FOREIGN KEY (GROUP_NUM) REFERENCES "GROUP"(GROUP_NUM)
);


CREATE SEQUENCE REPLY_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;

DROP TABLE REPLY;

SELECT REPLY_SEQ.nextval FROM DUAL;
SELECT REPLY_SEQ.currval FROM DUAL;

SELECT * FROM REPLY;

INSERT INTO REPLY
VALUES(1, 1, 'kbmin2','댓글 테스튼내용입니다. 댓글 테스트내용입니다.');

INSERT INTO REPLY 
VALUES(2, 1,'dfdd2','댓글 테스트2 입니다');

INSERT INTO REPLY 
VALUES(3, 1,'bkmin2','댓글 테스트3 입니다');

INSERT INTO RELPY
VALUES(REPLY_SEQ.nextval, 3, 'bkmin2', '테스트 댓글입니다.');

SELECT * FROM REPLY WHERE GROUP_NUM = ${group_num}
		ORDER BY REPLY_NUM DESC;


   SELECT * FROM
			(SELECT ROWNUM R, D.* FROM 
				(SELECT * FROM "GROUP_JOINED" ORDER BY GROUP_NUM DESC) D) B
				 WHERE B.R BETWEEN ${startRow} AND ${endRow} 
 

SELECT COUNT(*) FROM "GROUP_JOINED" 

-------------------------FILEDB-----------------

CREATE TABLE GROUP_FILES(
  FILE_NAME VARCHAR2(100),
  MEMBER_ID VARCHAR2(50),
  CONSTRAINTS GROUP_FILES_PK PRIMARY KEY(FILE_NAME),
  CONSTRAINTS GROUP_FILES_FK FOREIGN KEY(MEMBER_ID) REFERENCES "MEMBER"(MEMBER_ID)
 );

SELECT GROUP_SEQ.NEXTVAL FROM DUAL

DROP TABLE GROUP_FILES;
DELETE FROM REPLY WHERE REPLY_NUM = ${reply_num};
SELECT * FROM GROUP_FILES;




-----------------------test-----------------------
DELETE FROM "GROUP" WHERE GROUP_NUM = ${group_num};
DELETE FROM "GROUP_JOINED" WHERE GROUP_NUM = ${group_num};
SELECT * FROM "GROUP";
SELECT * FROM "GROUP" ORDER BY GROUP_NUM DESC;
 SELECT * FROM "GROUP" ORDER BY MEMBER_NUM ASC; 

SELECT * FROM GROUP_jOINED ORDER BY GROUP_NUM DESC;
SELECT COUNT(*) FROM "GROUP_JOINED";
SELECT * FROM
			(SELECT ROWNUM R, D.* FROM 
				(SELECT * FROM "GROUP_JOINED" ORDER BY GROUP_NUM DESC) D) B
				 WHERE B.R BETWEEN ${startRow} AND ${endRow};
				
SELECT * FROM V$VERSION;
CREATE TABLE test (
    id bigint(20) NOT NUMM AUTO_INCREMENT,
    content varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)

) ENGINE=InnoDB;

SELECT * FROM time_zone;
SELECT SYSDATE, SYSTIMESTAMP FROM DUAL;


